/* eslint-disable */
/** This is the code automatically generated by playground/scripts/genRouter
 *  please do not modify ;
 * 	See the configuration file: routes.yaml.
 * */
import React from 'react';
import { ControlOutlined, FormOutlined, WindowsFilled, ProfileOutlined } from '@ant-design/icons';

export default [
  {
    item: '工程化',
    key: '工程化',
    icon: <ControlOutlined />,

    children: [
      {
        item: 'crash信息收集',
        key: 'crash信息收集',

        path: '/engineering/crash',
      },
      {
        item: '开发',
        key: '开发',

        path: '/engineering/development',
      },
      {
        item: '打包',
        key: '打包',

        path: '/engineering/packaging',
      },
      {
        item: '自动更新',
        key: '自动更新',

        path: '/engineering/update',
      },
    ],
  },
  {
    item: '应用',
    key: '应用',
    icon: <FormOutlined />,

    children: [
      {
        item: '协议-从网页端唤起Electron应用',
        key: '协议-从网页端唤起Electron应用',

        path: '/application/protocol',
      },
      {
        item: 'Dialog与文件选择',
        key: 'Dialog与文件选择',

        path: '/application/dialog',
      },
      {
        item: '菜单',
        key: '菜单',

        path: '/application/menu',
      },
      {
        item: '系统托盘',
        key: '系统托盘',

        path: '/application/tray',
      },
      {
        item: '文件管理器',
        key: '文件管理器',

        path: '/application/file-manager',
      },
    ],
  },
  {
    item: '窗口管理',
    key: '窗口管理',
    icon: <WindowsFilled />,

    children: [
      {
        item: '创建和管理窗口',
        key: '创建和管理窗口',

        path: '/browser/window-operate',
      },
      {
        item: '主窗口隐藏和恢复',
        key: '主窗口隐藏和恢复',

        path: '/browser/awaken',
      },
      {
        item: '窗口的聚焦和失焦',
        key: '窗口的聚焦和失焦',

        path: '/browser/focus-blur',
      },
      {
        item: '全屏、最大化、最小化、恢复',
        key: '全屏、最大化、最小化、恢复',

        path: '/browser/window-fullscreen',
      },
      {
        item: '窗口通信',
        key: '窗口通信',

        path: '/browser/communication',
      },
      {
        item: '窗口类型',
        key: '窗口类型',

        path: '/browser/window-type',
      },
      {
        item: '窗口事件',
        key: '窗口事件',

        path: '/browser/window-event',
      },
    ],
  },
  {
    item: '其他',
    key: '其他',
    icon: <ProfileOutlined />,

    children: [
      {
        item: '安全性',
        key: '安全性',

        path: '/others/security',
      },
    ],
  },
];
