/* eslint-disable */
/**
 * This is the code automatically generated by playground/scripts/genRouter
 * please do not modify ;
 * See the configuration file: routes.yaml.
 */
import React, { Suspense, lazy } from 'react';
import { Switch, Route } from 'react-router-dom';

export default function () {
  return (
    <>
      <Suspense fallback={<div>Loading...</div>}>
        <Switch>
          <Route path="/engineering/crash" component={lazy(() => import('../page/engineering/crash'))} />
          <Route path="/engineering/development" component={lazy(() => import('../page/engineering/development'))} />
          <Route path="/engineering/packaging" component={lazy(() => import('../page/engineering/packaging'))} />
          <Route path="/engineering/update" component={lazy(() => import('../page/engineering/update'))} />
          <Route path="/application/protocol" component={lazy(() => import('../page/application/protocol'))} />
          <Route path="/application/dialog" component={lazy(() => import('../page/application/dialog'))} />
          <Route path="/application/menu" component={lazy(() => import('../page/application/menu'))} />
          <Route path="/application/tray" component={lazy(() => import('../page/application/tray'))} />
          <Route path="/application/file-manager" component={lazy(() => import('../page/application/file-manager'))} />
          <Route path="/browser/window-operate" component={lazy(() => import('../page/browser/window-operate'))} />
          <Route path="/browser/awaken" component={lazy(() => import('../page/browser/awaken'))} />
          <Route path="/browser/focus-blur" component={lazy(() => import('../page/browser/focus-blur'))} />
          <Route path="/browser/window-fullscreen" component={lazy(() => import('../page/browser/window-fullscreen'))} />
          <Route path="/browser/communication" component={lazy(() => import('../page/browser/communication'))} />
          <Route path="/browser/window-type" component={lazy(() => import('../page/browser/window-type'))} />
          <Route path="/browser/window-event" component={lazy(() => import('../page/browser/window-event'))} />
          <Route path="/others/security" component={lazy(() => import('../page/others/security'))} />
          <Route path="/demo/communication-part1/client" component={lazy(() => import('../page/browser-demo/communication-part1/client'))} />
          <Route path="/demo/communication-part1/main" component={lazy(() => import('../page/browser-demo/communication-part1/main'))} />
          <Route path="/demo/communication-part2/client" component={lazy(() => import('../page/browser-demo/communication-part2/client'))} />
          <Route path="/demo/communication-part2/main" component={lazy(() => import('../page/browser-demo/communication-part2/main'))} />
          <Route path="/demo/communication-part3/client" component={lazy(() => import('../page/browser-demo/communication-part3/client'))} />
          <Route path="/demo/communication-part3/main" component={lazy(() => import('../page/browser-demo/communication-part3/main'))} />
          <Route path="/demo/window-close" component={lazy(() => import('../page/browser-demo/window-close'))} />
          <Route path="/demo/window-type" component={lazy(() => import('../page/browser-demo/demo-window-type'))} />
          <Route path="/demo/full-screen" component={lazy(() => import('../page/browser-demo/full-screen'))} />
          <Route path="/editor" component={lazy(() => import('../page/editor'))} />
          <Route path="/download-manager/demo" component={lazy(() => import('../page/download-manager'))} />
          <Route path="/start" component={lazy(() => import('../page/start'))} />
          <Route path="/apidoc" component={lazy(() => import('../page/apidoc'))} />
        </Switch>
      </Suspense>
    </>
  );
}

export const isolatedRoutes = ['/demo/communication-part1/client', '/demo/communication-part1/main', '/demo/communication-part2/client', '/demo/communication-part2/main', '/demo/communication-part3/client', '/demo/communication-part3/main', '/demo/window-close', '/demo/window-type', '/demo/full-screen', '/editor', '/download-manager/demo', '/start', '/apidoc'];
